services:
  - type: web
    name: majiscope-community-connect
    runtime: node
    branch: main
    plan: free
    region: frankfurt
    autoDeployTrigger: commit
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NITRO_PRESET
        value: render_com
      - key: NODE_VERSION
        value: "22"

